---
format:
  html:
    toc: true
    toc-expand: true
    html-math-method: katex
#    html-math-method: mathjax
#    html-math-method: mathml
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
#header-includes:
#  - \usepackage{algorithm}
#   - \usepackage{amsmath}
#  - \usepackage{bm}
---

<!-- Compile with
quarto preview README.qmd --to html --no-browser --no-watch-inputs
quarto preview README.qmd --to html --no-browser
quarto render README.qmd --to html
-->

<font size="10">MY CS229</font>

# **Supervised Learning**

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="Class material" icon=false collapse=true}
* [Stanford CS229 on YouTube](https://youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU&si=kS07gMKIi_NB2Rlm){target="_blank"}
* [Handouts on Github](https://github.com/maxim5/cs229-2018-autumn){target="_blank"}, local copy at [cs229-2018-autumn/](./cs229-2018-autumn/){target="_blank"}
* [Notes](./cs229-2018-autumn/notes/) in `cs229-2018-autumn/notes/`
* [Python Tutorial](./cs229-2018-autumn/section/cs229_python_tutorial/cs229_python_friday.pdf){target="_blank"}
* [ml-yearning book](https://github.com/yennlh/ml-yearning){target="_blank"}
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="Class timeline" icon=false collapse=true}
* [Lecture 1](https://youtu.be/jGwO_UgTS7I?si=WSwUyA5wdGubuhKr)  
* [Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf)  
* [Problem Set 0](./cs229-2018-autumn/problem-sets/PS0/ps0.pdf), due on Lecture 4?  
* [Discussion Section: Linear Algebra](./cs229-2018-autumn/section/cs229-linalg.pdf)
* [Problem Set 1](./cs229-2018-autumn/problem-sets/PS1/ps1.pdf), due on Lecture 8
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="Note-1 --- Table of content" icon=false collapse=true}
* `Part I` [Linear Regression](#linear-regression)
    * `1` [LMS algorithm](#lms-algorithm)
    * `2` [The normal equations](#the-normal-equations)
        * `2.1` [Matrix derivatives](#matrix-derivatives)
        * `2.2` [Least squares revisited](#least-squares-revisited)
    * `3` [Probabilistic interpretation](#probabilistic-interpretation)
    * `4` [Locally weighted linear regression](#locally-weighted-linear-regression)
* `Part II` [Classification and Logistic Regression](#classification-and-logistic-regression)
    * `5` Logistic regression
    * `6` Digression: The perceptron learning algorithm
    * `7` Another algorithm for maximizing $l(\theta)$
* `Part III` [Generalized Linear Models](#generalized-linear-models)
    * `8` The exponential family
    * `9` Constructing GLMs
        * `9.1` Ordinary least squares
        * `9.2` Logistic regression
        * `9.3` Softmax Regression
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-1 @ 2018-09-24" icon=false collapse=true}
* [Lecture-1](https://youtu.be/jGwO_UgTS7I?si=2IdRH-7qmpdGYaBS){target="_blank"}, `https://youtu.be/jGwO_UgTS7I?si=2IdRH-7qmpdGYaBS`
* [Lecture-1 starts @ 36:20](https://youtu.be/jGwO_UgTS7I?si=aOaDLuqM2u4Sp_Dj&t=2180){target="_blank"}
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-1 --- Other CS229 classes" icon=false collapse=true}
* [Lecture 1 @ 35:20](https://youtu.be/jGwO_UgTS7I?si=aOaDLuqM2u4Sp_Dj&t=2120)  
* CS229a is more applied (is it the one on Coursera?)  
* CS229 most mathematical   
* CS230 deep learning  
::::

[Lecture-1 @ 39:34](https://youtu.be/jGwO_UgTS7I?si=aOaDLuqM2u4Sp_Dj&t=2374), `https://youtu.be/jGwO_UgTS7I?si=aOaDLuqM2u4Sp_Dj&t=2374`  
[Note-1](cs229-2018-autumn/notes/cs229-notes1.pdf), `cs229-2018-autumn/notes/cs229-notes1.pdf`

<!-- # Supervised Learning -->
* See the `housing price` example in [Note-1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 1.

Training set 

$$\{(\bm x^{(i)}, y^{(i)}); i = 1, \ldots, m\}$$

* $(\bm x^{(i)}, y^{(i)})$: a training example
* $m$: number of examples
* $\bm x$: input
* $y$: output

Hypothesis

$$h: \mathcal{X} \mapsto \mathcal{Y}$$

such that $h(\bm x) \approx y$.

* If $y$ is continuous $\rightarrow$ **regression problem**
* If $y$ is discrete $\rightarrow$ **classification problem**

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-1 --- Five topics of machine learning" icon=false collapse=true}
* Supervised learning, [Lecture 1@39:34](https://youtu.be/jGwO_UgTS7I?si=aOaDLuqM2u4Sp_Dj&t=2374)
* Machine learning strategy, [Lecture 1@58:19](https://youtu.be/jGwO_UgTS7I?si=Zp7HmdCk4g7Ul6Pd&t=3499)
* Deep learning, [Lecture 1@1:04:06](https://youtu.be/jGwO_UgTS7I?si=MiGzHLya5JawEoyb&t=3846)
* Unsupervised learning, [Lecture 1@1:04:55](https://youtu.be/jGwO_UgTS7I?si=KzVPsuc5X0GrUjk7&t=3895)
* Reinforcement learning, [Lecture 1@1:11:18](https://youtu.be/jGwO_UgTS7I?si=7al9kavU1hUy5g9I&t=4278)
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-2 @ 2018-09-26" icon=false collapse=true}
* [Lecture-2](https://youtu.be/4b4MUYve_U8?si=fWcooAh8yaYWXHPA), `https://youtu.be/4b4MUYve_U8?si=fWcooAh8yaYWXHPA`
* The housing example, [Lecture 2 @ 2:39](https://youtu.be/4b4MUYve_U8?si=x9f1zW1no4TAYxAl&t=159), [Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 1  
* Supervised learning, [Lecture 2 @ 3:01](https://youtu.be/4b4MUYve_U8?si=RrWTO1ZCVGdTQ4VC&t=181), [Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 1  
* Hypothesis diagram,  [Lecture 2 @ 3:12](https://youtu.be/4b4MUYve_U8?si=muE-BHqu9gcAF3Qo&t=192), [Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 2
* Linear regression,   [Lecture 2 @ 4:51](https://youtu.be/4b4MUYve_U8?si=kOpmyaQ-pbVZWoUD&t=291), [Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 3  
::::

[Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 3

# **Linear Regression**
Let the hypothesis, $h$, be a linear function
$$h(\bm x) = \theta_0x_0 + \theta_1x_1 + \dots + \theta_nx_n$$



Choose $\theta$ such that $h(\bm x) \approx y$.

<!--
= \sum_{j=0}^n \theta_jx_j
* Let $h(\bm x) = \sum_{j=0}^n \theta_jx_j$
* Choose $\theta$ such that $h \approx y$
-->

[Lecture-2 @ 7:54](https://youtu.be/4b4MUYve_U8?si=g7HG_okUwJNCbb0V&t=474)

<!--
:::
DO NOT REMOVE
:::
-->
:::: {.callout-note .my-callout title="Example" icon=false collapse=true}
For $n=2$,

$$h(\bm x) = \theta_0x_0 + \theta_1x_1 + \theta_2x_2 \approx y$$

* $x_0 = 1$
* $x_1$: size of the house
* $x_2$: number of bedrooms
* $\bm \theta$: parameters to be calculated
* $y$: price of the house
::::



General form of the linear function

$$h(\bm x^{(i)}) = h^{(i)} = \sum_{j=0}^n \theta_jx_j^{(i)} = \bm{x}^{(i)^T}\bm{\theta}$$

* $i$: index of training example
* $j$: index of features
* $m$: number of training examples, $\{i: 1 \le i \le m\}$
* $n$: number of features, $\{j: 0 \le j \le n \}$
* $\bm \theta$, parameters, size is $n+1$
* $(\bm x^{(i)},y^{(i)})$: $i^\text{th}$ training example  
* See [matrix](#matrix-derivatives) for the matrix form

<!--
In matrix form

$$\bm h = \begin{bmatrix} 
 & \bm x^{(1)^T} \\ 
 & \bm x^{(2)^T} \\ 
 & \cdot         \\
 & \cdot         \\
 & \bm x^{(m)^T} 
\end{bmatrix} = \bm X \bm\theta \approx \bm{y}
$$

* $\bm h^{m\times 1}$: hypothesis
* $\bm X^{m\times n}$: inputs/features
* $\bm y^{m\times 1}$: outputs/target variables
-->

[Lecture 2 @ 12:50](https://youtu.be/4b4MUYve_U8?si=4-Wq6xCgYbF6-sYb&t=770){target="_blank"}

* Note $h(\bm{x})$ somethime is written as $h_\theta(\bm{x})$ to emphasize parameters $\bm\theta$
* Choose $\bm{\theta}$ such that $h_{\bm\theta}(\bm{x}) \approx y$ for training examples

Define the **cost function**

$$
\begin{align*}
J(\bm\theta) &= \frac{1}{2}\sum_{i=1}^{m}(h^{(i)} - y^{(i)})^2 \\
             &= \frac{1}{2}\sum_{i=1}^{m}(\theta_0 + \theta_1x_1^{(i)} + \theta_2x_2^{(i)} + \ldots+ \theta_nx_n^{(i)} - y^{(i)})^2  \\
\end{align*}
$$

[Lecture-2 @ 16:10](https://youtu.be/4b4MUYve_U8?si=4-Wq6xCgYbF6-sYb&t=970){target="_blank"}

and find $\bm\theta$ that minimize $J(\bm\theta)$.

[Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 4

# LMS algorithm

[Lecture-2 @ 18:13](https://youtu.be/4b4MUYve_U8?si=3NGQOHHU1xN6yAxp&t=1093){target="_blank"}

## Gradient descent
* Gradient descent is an algorithm to search for the least mean squares, $\min J(\theta)$. 
* Initial guess $\bm\theta = \vec{0}$  
* Keep change $\bm\theta$ to reduce $J(\bm\theta)$  

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-2 --- 3D plot" icon=false collapse=true}
* [Lecture-2 @19:58](https://youtu.be/4b4MUYve_U8?si=3NGQOHHU1xN6yAxp&t=1198){target="_blank"}
    * Gradient descent (in the steepest direction)  
    * Step of gradient descent
::::

[Lecture-2 @ 23:54](https://youtu.be/4b4MUYve_U8?si=3NGQOHHU1xN6yAxp&t=1434){target="_blank"}

$$
\theta_j := \theta_j - \alpha\frac{\partial}{\partial\theta_j}J(\bm\theta)
$$

where

* $\alpha$: learning rate.  

Set $\alpha = 0.01$ in practice, [Lecture-2 @ 26:04](https://youtu.be/4b4MUYve_U8?si=rp_57eeGH42uDfuo&t=1564){target="_blank"}

[Lecture-2 @ 30:27](https://youtu.be/4b4MUYve_U8?si=rp_57eeGH42uDfuo&t=1827){target="_blank"}

Recall $h = h(\bm\theta,\bm x)$, so the partial derivative is
$$
\begin{align*}
\frac{\partial J(\bm\theta) }{\partial\theta_j}
 &=  \frac{1}{2}\sum_{i=1}^{m}\frac{\partial}{\partial\theta_j}(h^{(i)} - y^{(i)})^2 \\
 & = \frac{1}{2}\sum_{i=1}^{m} 2 \cdot (h^{(i)} - y^{(i)}) \cdot 
       \frac{\partial}{\partial\theta_j}(h^{(i)} - y^{(i)}) \\
 & = \sum_{i=1}^{m}(h^{(i)} - y^{(i)}) \cdot 
       \frac{\partial}{\partial\theta_j}(\sum_{j=0}^n \theta_jx_j^{(i)} - y^{(i)}) \\
 & = \sum_{i=1}^{m}(h^{(i)} - y^{(i)}) \cdot x_j^{(i)} \\         
\end{align*}
$$

In summary
$$
\begin{align*}
\theta_j &:= \theta_j - \alpha\sum_{i=1}^{m}(h^{(i)} - y^{(i)}) \cdot x_j^{(i)} \\
\end{align*}
$$

* LMS update rule (Widrow-Hoff learning rule)
* the update is proportional to the error, $(h^{(i)} - y^{(i)})$
* $\alpha$: learning rate
* $J(\bm\theta)$ is a convex quadratic function

**Batch gradient descent** could be slow with large data set.


<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="Batch gradient descent" icon=false collapse=false}
$$
\begin{align*}
&\text{while}\ J(\bm\theta)\  \text{is not converged}\\
&\qquad \text{for}\ j = 1:n \quad\text{\footnotesize\# parameters} \\
&\qquad\qquad \theta_j := \theta_j - \alpha\sum_{i=1}^{m}(h^{(i)} - y^{(i)}) \cdot x_j^{(i)} \\
&\qquad \text{end} \\
&\text{end}
\end{align*}
$$
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="Batch gradient descent in Julia" icon=false collapse=true}
```julia
# Batch gradient descent
# size(x) == (m,n)
# size(y) == (m,)
# m >> n

function converged()
    # TODO, check J(θ)
end

h(θ,v) = dot(θ,v)
while !converged()
    for j in 1:n      # parameters
        acc = 0.0     # accumulation
        for i in 1:m  # training examples
            acc += (h(θ,x[i,:]) - y[i]) * x[i,j]
        end
        θ_new[j] = θ[j] - ⍺*acc
    end
    θ .= θ_new 
end
```
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-2" icon=false collapse=true}
* 3D plot, [Lecture 2@34:26](https://youtu.be/4b4MUYve_U8?si=2W825SRd4Om_MIOe&t=2066){target="_blank"}
* Try $\alpha$ by $0.01, 0.02, 0.04, 0.08 \ldots$.  
* 2D plot, [Lecture 2@37:25](https://youtu.be/4b4MUYve_U8?si=2W825SRd4Om_MIOe&t=2245){target="_blank"}
::::
<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-caution .my-callout title="TODO" icon=false collapse=true}
```julia
# Repeat until convergence
# size(x) == (m,n)
# m >> n
# θ[n], x[m,n], y[m]
for j in 1:n     # parameters
    acc = 0.0    # accumulation
    for i in 1:m # training examples
        acc += (y[i] - x[i:i,:]*θ)*x[i,j]
    end
    θ[j] = θ[j] + ⍺ * acc
end

# zero index will be a problem in Julia
h(i,j) = θ0 + θ1*x[i,j]
for j in 1:n # parameters
    s = 0.0
    for i in 1:m # examples
        s += (y[i] - h(i,j))*x[i,j]
    end
    θ[j] = θ[j] + ⍺ * s
end



h = x * θ
#   n   1  nxm     mx1
θ = θ + ⍺ * x' * (y - h)
```
::::

[Lecture-2 @ 44:47](https://youtu.be/4b4MUYve_U8?si=vGQnctfr3f7uigsP&t=2687){target="_blank"}  
[Note-1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 7

**Stochastic gradient descent** is **faster** than batch gradient descent.

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="Stochastic gradient descent" icon=false collapse=false}

$$
\begin{align*}
&\text{while}\ J(\bm\theta)\ \text{is not converged}\\
&\qquad\text{for}\ i = 1:m  \quad\text{\footnotesize \# training data} \\
&\qquad\qquad\text{for}\ j = 1:n  \quad\text{\footnotesize \# parameters} \\
&\qquad\qquad\qquad \theta_j := \theta_j - \alpha(h^{(i)} - y^{(i)})\cdot x_j^{(i)} \\
&\qquad\qquad\text{end} \\
&\qquad\text{end} \\
&\text{end}
\end{align*}
$$ 
::::

The learning rate, $\alpha$, could be reduced over time.

<!--
:::
DO NOT REMOVE
:::
-->
::: {.callout-note .my-callout title="Stochastic gradient descent in Julia" icon=false collapse=true}

```julia
using LinearAlgebra
h(u,v) = dot(u,v)
while !converged()
    for i in 1:m # training data
        θ .-= ⍺ * (h(θ,x[i,:]) - y[i]) * transpose(x[i,:])
    end
end
```
:::


[Lecture-2 @ 53:51](https://youtu.be/4b4MUYve_U8?si=j2zZ4OXJSM4CO52b&t=3231){target="_blank"}  
[Note-1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 7


# The normal equations

* Only works for linear regression
* Analytical solution of $\bm\theta$ to $\min J(\bm\theta)$


[Lecture-2 @ 56:36](https://youtu.be/4b4MUYve_U8?si=wT_tj5E-IWv74IBT&t=3396)

<!--
:::
DO NOT REMOVE
:::
-->
::: {.callout-note .my-callout title="$\nabla_{\bm\theta} J(\bm\theta)$" icon=false collapse=false}
$$\theta \in \mathbb{R}^{n+1}$$
$$
\nabla_{\bm\theta} J(\bm\theta) = \nabla J(\bm\theta) = 
\begin{bmatrix}
\partial J/\partial \theta_0 \\
\partial J/\partial \theta_1 \\
\cdot \\
\partial J/\partial \theta_n \\
\end{bmatrix}
$$
:::
<!--
:::
DO NOT REMOVE
:::
-->
::: {.callout-note .my-callout title="Example" icon=false collapse=true}
$$n=2$$
$$
\nabla_{\bm\theta} J(\bm\theta) = 
\begin{bmatrix}
\partial J/\partial \theta_0 \\
\partial J/\partial \theta_1 \\
\partial J/\partial \theta_2 \\
\end{bmatrix}
$$
:::

[Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 8

## Matrix derivatives
* Properties of matrix derivatives and trace.  
* Prerequisite of solving the normal equations.

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="TODO" icon=false collapse=true}
Note 1 trace properties
:::: 
<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-2 --- Matrix derivatives" icon=false collapse=false}
* [Lecture-2 @ 1:00:02](https://youtu.be/4b4MUYve_U8?si=wQGqaMwfErzCM6So&t=3602){target="_blank"}

$$\bm A \in \mathbb R^{2\times 2}$$ 
$$f : \mathbb R^{2\times 2} \mapsto \mathbb R$$
$$
\nabla_{\bm A}f(\bm A) = 
\begin{bmatrix}
\dfrac{\partial f}{\partial A_{11}} & \dfrac{\partial f}{\partial A_{12}} \\[1em]
\dfrac{\partial f}{\partial A_{21}} & \dfrac{\partial f}{\partial A_{22}} \\
\end{bmatrix}
$$

$J(\bm\theta)$ is minimum when $\nabla_{\bm\theta} J(\bm\theta) = \vec{0}$.  
Minimize $J(\bm\theta)$ by solving $\nabla_{\bm\theta} J(\bm\theta) = \vec{0}$.  
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-2 --- Trace operation" icon=false collapse=false}
* [Lecture 2@1:03:42](https://youtu.be/4b4MUYve_U8?si=zoAsvcX1FLkZ1rKQ&t=3822){target="_blank"}

$$
\begin{align*}
\bm A &\in \mathbb R^{n\times n}  \\
\text{tr}(\bm A) &= \sum_{i=1}^n A_{ii} \\
\operatorname{tr}(\bm A) &= \operatorname{tr}(\bm A^T) \\
\nabla_{\bm A}\operatorname{tr}(\bm A \bm B) &= \bm B^T \\
\operatorname{tr}(\bm A \bm B) &= \operatorname{tr}(\bm B \bm A) \\
\operatorname{tr}(\bm A\bm B \bm C) &= \operatorname{tr}(\bm C \bm A \bm B) \\
\nabla_{\bm A}\operatorname{tr}(\bm A\bm B\bm A^T\bm C) &= \bm C\bm A\bm B + \bm C^T\bm A\bm B^T \\
\nabla_{\bm A}\operatorname{tr}(\bm A\bm A^T\bm C) &= \bm C\bm A + \bm C^T\bm A \\
\end{align*}
$$
::::


<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-warning .my-callout title="Proof of $\operatorname{tr}(\bm A \bm B) = \operatorname{tr}(\bm B \bm A)$" icon=false collapse=true}

$$
\begin{align*}
\operatorname{tr}(\bm A \bm B) &= \sum_{i=1}^n A_{1i}B_{i1} + \sum_{i=1}^n A_{2i}B_{i2} + \cdots + \sum_{i=1}^n A_{ni}B_{in} \\
                               &= \sum_{j=1}^n \sum_{i=1}^n A_{ji}B_{ij} \\
\operatorname{tr}(\bm B \bm A) &= \sum_{j=1}^n B_{1j}A_{j1} + \sum_{i=j}^n B_{2j}A_{j2} + \cdots + \sum_{j=1}^n B_{nj}A_{jn} \\
                               &= \sum_{i=1}^n \sum_{j=1}^n B_{ji}A_{ji} = \sum_{j=1}^n \sum_{i=1}^n A_{ji}B_{ij} \\
\operatorname{tr}(\bm A \bm B) &= \sum_{j=1}^n \sum_{i=1}^n A_{ji}B_{ij} = \operatorname{tr}(\bm B \bm A)
\end{align*}
$$
::::

[Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 9

## Least squares revisited
* design matrix, $X$
* normal equation
* pseudo inverse
* $\bm{\theta} = (\bm{X}^T\bm{X})^{-1}\bm{X}^T\bm{y}$

[Lecture-2 @ 1:07:54](https://youtu.be/4b4MUYve_U8?si=XGgKoLo0kARmTkHq&t=4074){target="_blank"}


$$
\bm X\bm\theta = \begin{bmatrix}
x^{(1)}_0 & x^{(1)}_1 & x^{(1)}_2 \\
x^{(2)}_0 & x^{(2)}_1 & x^{(2)}_2 \\
x^{(3)}_0 & x^{(3)}_1 & x^{(3)}_2 \\
x^{(4)}_0 & x^{(4)}_1 & x^{(4)}_2 \\
\end{bmatrix} \begin{bmatrix}
\theta_0 \\
\theta_1 \\
\theta_2 \\
\end{bmatrix} = \begin{bmatrix}
(\bm x^{(1)})^T\\
(\bm x^{(2)})^T\\
(\bm x^{(3)})^T\\
(\bm x^{(4)})^T\\
\end{bmatrix} \bm\theta = \begin{bmatrix}
h^{(1)} \\
h^{(2)} \\
h^{(3)} \\
h^{(4)} \\
\end{bmatrix}
$$
$$
\bm X\bm\theta -\bm y = \begin{bmatrix}
h^{(1)} - y^{(1)} \\
h^{(2)} - y^{(2)} \\
h^{(3)} - y^{(3)} \\
h^{(4)} - y^{(4)} \\
\end{bmatrix}
$$

[Lecture-2 @ 1:11:12](https://youtu.be/4b4MUYve_U8?si=t5XUoooWbY3aXYMK&t=4272){target="_blank"}

$$
\begin{align*}
J(\bm\theta) &= \frac{1}{2}\sum_{i=1}^{m}(h^{(i)} - y^{(i)})^2 \\
             &= \frac{1}{2}(\bm X\bm\theta - \bm y)^T(\bm X\bm\theta - \bm y) = \frac{1}{2} \| \bm{X}\bm\theta - \bm{y}\|_ 2^2
\end{align*}
$$

[Lecture 2@1:13:16](https://youtu.be/4b4MUYve_U8?si=HZb_uHJVLOCVx3jo&t=4396){target="_blank"}

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="$\nabla_{\bm\theta} J(\bm\theta) = \bm{X}^T\bm{X}\theta - \bm{X}^T\bm{y}$" icon=false collapse=true}
$$
\begin{align*}
\nabla_{\bm\theta} J(\bm\theta) &= \nabla J(\bm\theta) \\
&= \frac{1}{2}\nabla(\bm X\bm\theta - \bm y)^T(\bm X\bm\theta - \bm y) \\
&= \frac{1}{2}\nabla(\bm\theta^T\bm X^T - \bm y^T)(\bm X\bm\theta - \bm y) \\
&= \frac{1}{2}\nabla(\bm\theta^T\bm X^T\bm X\bm\theta - \bm\theta^T\bm X^T\bm y - 
\bm y^T\bm X\bm\theta + \bm y^T\bm y) \\
&= \frac{1}{2}\nabla(\bm\theta^T\bm X^T\bm X\bm\theta - \bm\theta^T\bm X^T\bm y - 
\bm y^T\bm X\bm\theta) \quad \footnotesize \bm y^T\bm y \ \text{is not a function of}\ \theta\\
&= \frac{1}{2}\nabla\operatorname{tr}(\bm\theta^T\bm X^T\bm X\bm\theta - \bm\theta^T\bm X^T\bm y - 
\bm y^T\bm X\bm\theta) \quad \text{\footnotesize \# scalar = trace of a scalar} \\
&= \frac{1}{2}\nabla\operatorname{tr}(\bm\theta^T\bm X^T\bm X\bm\theta) - \frac{1}{2}\nabla\operatorname{tr}(\bm\theta^T\bm X^T\bm y + \bm y^T\bm X\bm\theta) \quad \text{\footnotesize \# re-group}\\
&= \frac{1}{2}\nabla\operatorname{tr}(\bm\theta^T\bm X^T\bm X\bm\theta) - \nabla\operatorname{tr}(\bm y^T\bm X\bm\theta) \quad \footnotesize \#\ \operatorname{tr}(A) = \operatorname{tr}(\bm A^T)\\
&= \bm{X}^T\bm{X}\theta - \bm{X}^T\bm{y} \quad \footnotesize \#\ \text{see details below} \\ 
\end{align*}
$$
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="Details" icon=false collapse=true}
$$
\begin{align*}
\frac{1}{2}\nabla\operatorname{tr}(\bm\theta^T\bm X^T\bm X\bm\theta) 
&= \frac{1}{2}\nabla\operatorname{tr}(\bm\theta\bm\theta^T\bm X^T\bm X) \quad\footnotesize\#\ \operatorname{tr}(ABC) = \operatorname{tr}(CAB)\\
&= \frac{1}{2}(\bm X^T\bm{X\theta} + \bm{X}^T\bm{X}\theta) \quad\footnotesize\#\ \nabla_A tr A A^T C = CA + C^TA\\
&= \bm X^T\bm{X\theta}\\
\\
\nabla\operatorname{tr}(\bm y^T\bm X\bm\theta) 
&= \nabla\operatorname{tr}(\bm{\theta}\bm{y}^T\bm{X}) \quad\footnotesize\#\ \operatorname{tr}(ABC) = \operatorname{tr}(CAB)\\
&= \bm{X}^T\bm{y} \quad\footnotesize\#\ \nabla_A\operatorname{tr}(AB) = B^T \\
\end{align*}
$$
::::
<!--
:::
DO NOT REMOVE
:::
-->

$J(\bm\theta)$ is at minimum when $\nabla J(\bm\theta) = 0.$

$$
\begin{align*}
\nabla J(\bm\theta) = &\bm{X}^T\bm{X}\theta - \bm{X}^T\bm{y} = 0\\
&\bm{X}^T\bm{X}\theta = \bm{X}^T\bm{y} \\
\\
&\bm{\theta} = (\bm{X}^T\bm{X})^{-1}\bm{X}^T\bm{y} \\
\end{align*}
$$ 

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-note .my-callout title="Normal equations naming reason" icon=false collapse=false}
* See [WPI Handout](https://users.wpi.edu/~walker/MA3257/HANDOUTS/least-squares_handout.pdf)

Normal equations are called normal (orthogonal) equations because

$$
\begin{align*}
\bm{X}^T\bm{X}\theta - \bm{X}^T\bm{y} = 0 \\
\bm{X}^T(\bm{X}\theta - \bm{y}) = 0 \\
\end{align*}
$$

$(\bm{X}\theta - \bm{y})$ is orthogonal to $\bm{X}^T$.
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Discussion-1 @ 2018-09-28" icon=false collapse=true}
* Linear Algebra Review and Reference
* [cs229-2018-autumn/section/cs229-linalg.pdf](./cs229-2018-autumn/section/cs229-linalg.pdf)
::::

<!--
:::
DO NOT REMOVE
:::
-->
::::{.callout-tip .my-callout title="Lecture-3 @ 2018-10-01" icon=false collapse=true}
* [Lecture-3](https://youtu.be/het9HFqo1TQ?si=D7whfKL91tddccLg), `https://youtu.be/het9HFqo1TQ?si=D7whfKL91tddccLg`
* Outline
    * Recap of linear regression
    * Locally weighted linear regression
    * Probabilistic interpretation
    * Logistic regression
    * Newton's method
::::

[Lecture-3 @ 1:26](https://youtu.be/het9HFqo1TQ?si=-zl8bI7wKl-bW_za&t=86){target="_blank"}

**Recap of linear regression**

* $(x^{(i)},y^{(i)})$: the i^th^ example
* $\bm{x}^{(i)} \in \R^{n+1}, x^{(i)}_0 = 1$
* $y^{(i)} \in \R$
* $m$: No. of examples
* $n$: No. of features
* $h(\bm{x}) = \sum_{j=0}^n \theta_j x_j = \theta^Tx$
* $J(\theta) = \frac{1}{2}\sum_{i=1}^{m}(h(\bm{x}^{(i)}) - y^{(i)})^2$



[Lecture-3 @ 2:23](https://youtu.be/het9HFqo1TQ?si=-zl8bI7wKl-bW_za&t=143){target="_blank"}

Feature selection algorithm will be introduced

[Lecture-3 @ 5:55](https://youtu.be/het9HFqo1TQ?si=-zl8bI7wKl-bW_za&t=355){target="_blank"}  

[Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 13

# Locally weighted linear regression

**Parametric** learning algorithm

* un-weighted
* Fit fixed set of parameters $(\theta_i)$ to data

$$
J(\bm\theta) = \frac{1}{2}\sum_{i=1}^{m}(h^{(i)} - y^{(i)})^2
$$

**Non-parametric** learning algorithm

* weighted
* Amount of data/parameters need to keep grows linearly with the size of the data

$$
J(\bm\theta) = \frac{1}{2}\sum_{i=1}^{m}w^{(i)}(h^{(i)} - y^{(i)})^2
$$

One choice for the weight is
$$
w^{(i)} = exp\left({\frac{-(x^{(i)}-x)^T(x^{(i)}-x)}{2\tau^2}}\right)
$$

* $\tau$, bandwidth


[Lecture-3 @ 21:56](https://youtu.be/het9HFqo1TQ?si=-zl8bI7wKl-bW_za&t=1316){target="_blank"}  
[Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 11

# Probabilistic interpretation

* Why linear regression?
* Why least square cost function?  
* Least square regression could be derived from a set of probabilistic assumption.
* Normal distribution in terms of $\theta$, [Lecture 3@29:15](https://youtu.be/het9HFqo1TQ?si=-zl8bI7wKl-bW_za&t=1755)
* Central limit theorem, [Lecture 3@35:56](https://youtu.be/het9HFqo1TQ?si=-zl8bI7wKl-bW_za&t=2156)
* Maximum likelihood estimation, [Lecture 3@41:03](https://youtu.be/het9HFqo1TQ?si=-zl8bI7wKl-bW_za&t=2463)




[Lecture-3 @ 43:36](https://youtu.be/het9HFqo1TQ?si=NBActVemQDQQ6RyJ&t=2616){target="_blank"}

# **Classification and logistic regression**


[Lecture-3 @ 45:58](https://youtu.be/het9HFqo1TQ?si=NBActVemQDQQ6RyJ&t=2758){target="_blank"}

TODO: definition of $h$

# Logistic regression
* Want $h_\theta(x) \in [0,1]$
* Batch gradient descent, Time: 1:02:09

[Lecture-3 @ 1:02:09](https://youtu.be/het9HFqo1TQ?si=NBActVemQDQQ6RyJ&t=3729){target="_blank"}

$$
\theta_j := \theta_j + \alpha \sum_{i=1}^m (y^{(i)} - h_\theta(x^{(i)})) x_j^{(i)}
$$

[Lecture-3 @ 1:05:31](https://youtu.be/het9HFqo1TQ?si=NBActVemQDQQ6RyJ&t=3931){target="_blank"}  

[Note 1](./cs229-2018-autumn/notes/cs229-notes1.pdf), p. 20

# Another algorithm for maximizing $l(\theta)$
* Newton's method

# Digression: The perceptron learning algorithm

# **Generalized Linear Models**
* [Lecture 4](https://youtu.be/iZTeva0WSTQ?si=adSzsWr66pQLrJa0)

# The exponential family

# Constructing GLMs

See the [syllabus](./cs229-2018-autumn/syllabus-autumn2018.html) for the timing of problem sets

[Problem Set 0](./cs229-2018-autumn/problem-sets/PS0/ps0.pdf)



Margin

Margin

Margin

Margin

Margin

Margin

Margin

Margin

Margin
