<!-- 
quarto preview c:/Users/yi-kun.yang/work/org.allnix.work/tiny_c_projects/README.md --no-browser --no-watch-inputs
-->
**PREFACE**

* delightful aspect of programming: instant feedback
* [C for Dummies](https://c-for-dummies.com/blog/)


# 2 Daily greetings

* `ps -p $$`, where `$$` is one of the parameter expansion in bash

## 2.2

### 2.2.1 Coding a greeting
```c
// Listing 2.1, page 21
// greet01.c
#include <stdlib.h>
#include <stdio.h>

int main() {
    printf("Hello Yi-Kun!\n");

    return EXIT_SUCCESS;
}
```
### 2.2.2 Adding a name as an argument
```c
// Listing 2.2, page 22
// greet02.c
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {

    if (argc < 2) {
        puts("Hello!");
    } else {
        printf("Hello, %s!\n", argv[1]);
    }

    return EXIT_SUCCESS;
}
```
## 2.3 The time of day

### 2.3.1 Obtaining the current time
```c
// Listing 2.3, page 23
// time01.c

#include <stdlib.h>
#include <stdio.h>
#include <time.h>

int main() {
    time_t now;
    time(&now);

    printf("The computer thinks it is %ld\n", now);
    // printf("%s", ctime(&now)); // deprecated
        
    char buf [80];
    strftime(buf, 80, "%a %b %d %H:%M:%S %Y", localtime(&now)); // Fri Jan 30 14:50:20 2026
    puts(buf);

    return EXIT_SUCCESS;
}
```
```c
// Listing 2.4, page 24
// time02.c

#include <stdlib.h>
#include <stdio.h>
#include <time.h>

int main() {
    time_t now;
    struct tm *clock;

    time(&now);
    clock = localtime(&now); // clock points to internal static memory

    puts("Time details:");
    printf(" Day of the year: %d\n", clock->tm_yday);
    printf(" Day of the week: %d\n", clock->tm_wday);
    printf("            Year: %d\n", clock->tm_year+1900);
    printf("           Month: %d\n", clock->tm_mon);
    printf("Day of the month: %d\n", clock->tm_mday);
    printf("            Hour: %d\n", clock->tm_hour);
    printf("          Minute: %d\n", clock->tm_min);
    printf("          Second: %d\n", clock->tm_sec);

    return EXIT_SUCCESS;
}
```

### 2.3.2 Mixing in the general time of day


```c
// Listing 2.5, page 25
// greet03.c
```

### 2.3.3 Adding specific time info

```c
// Listing 2.6, page 26
// greet04.c
```

## 2.4 The current moon phase

### 2.4.1 Observing moon phases
### 2.4.2 Writing the moon phase algorithm
```c
// Listing 2.7, page 29
// greet04.c
// moon_phase()
```
### 2.4.3 Adding the moon phase to your greeting
## 2.5 A pithy saying
### 2.5.1 Creating a pithy phrase repository
### 2.5.2 Randomly reading a pithy phrase
```c
// Listing 2.8, page 33
// pithy01.c, page 33: Read file, print and close
// pithy02.c, page 34: Allocate memory for one line of text
// pithy03.c, page 34: Save all text into list_base
// pithy04.c, page 36: Increase the size of list_base if necessary
// pithy05.c, page 37: Print one random pithy
```

* `realloc()`

### 2.5.3 Adding the phrase to your greeting code

# 3 NATO output

## 3.1 The NATO alphabet
```default
A Alfa       N November
B Bravo      O Oscar
C Charlie    P Papa
D Delta      Q Quebec
E Echo       R Romeo
F Foxtrot    S Sierra
G Golf       T Tango
H Hotel      U Uniform
I India      V Victor
J Juliet     W Wiskey
K Kilo       X X-Ray
L Lima       Y Yankee
M Mike       Z Zulu
```
## 3.2 The NATO translator program
### 3.2.1 Writing the NATO translator
```c
// Listing 3.1, page 41
// nato01.c, page 41
// Turn keyboard input into NATO phonetic.
```
### 3.2.2 Reading and converting a file
```c
// Listing 3.2, page 42
// nato02.c, page 42
// Read from file and turn characters into NATO phonetic.
```
## 3.3 From NATO to English
### 3.3.1 Converting NATO input to character output
* `strtok()`

```c
// Listing 3.3, page 44
// word_parse01.c, page 44
// Tokenize a string from keyboard.
```

```c
// Listing 3.4, page 46
// nato03.c, isterm()
// Convert NATO phonetic word to its first character.
```

```c
// Listing 3.5, page 46
// nato03.c
// Turn keyboard input from NATO phonetic into character.
```

### 3.3.2 Reading NATO input from a file
```c
// Listing 3.6, page 48
// nato04.c, based on nato03.c add nato02.c
// Scan NATO phonetic word and translate into alphabetic 
```

```c
//Listing 3.7, page 48
// nato05.c, based on nato04.c
// Scan word by word instead of 64-character at a time
// to avoid incomplete reading of a word
```
